In [190]:
atk = pd.read_csv("/Users/kimjeongseob/Desktop/Study/0.Project/2. Regression Anlaysis/5. Model tuning/1. weighting data/0. dataset/1. before/df_atk.csv")
dfd = pd.read_csv("/Users/kimjeongseob/Desktop/Study/0.Project/2. Regression Anlaysis/5. Model tuning/1. weighting data/0. dataset/1. before/df_dfd.csv")
mdf = pd.read_csv("/Users/kimjeongseob/Desktop/Study/0.Project/2. Regression Anlaysis/5. Model tuning/1. weighting data/0. dataset/1. before/df_mdf.csv")

In [191]:
atk = atk.drop(columns = 'Unnamed: 0')
dfd = dfd.drop(columns = 'Unnamed: 0')
mdf = mdf.drop(columns = 'Unnamed: 0')

In [192]:
atk.shape, dfd.shape, mdf.shape

((95, 39), (95, 39), (151, 39))

In [193]:
col_other = ['player_name','position','age','height','weight','rating','value','follower','games_played']
col_atk = ['goals_total','goals_assists']
col_basic = ['shots_on','passes_key','dribbles_success']
col_dfd = ['tackles_blocks','tackles_interceptions','fouls_drawn','fouls_committed']
col_cont = ['duels_won']

In [194]:
col_ = col_atk+col_basic+col_dfd+col_cont+['value','follower','age']

In [195]:
len(col_)

13

In [196]:
atk = atk[col_]

In [197]:
dfd = dfd[col_]
mdf = mdf[col_]

In [198]:
atk.shape, dfd.shape, mdf.shape

((95, 13), (95, 13), (151, 13))

In [199]:
atk

,goals_total,goals_assists,shots_on,passes_key,dribbles_success,tackles_blocks,tackles_interceptions,fouls_drawn,fouls_committed,duels_won,value,follower,age
0,0.4432,0.0985,1.0538,0.9554,0.9947,0.0985,0.2659,2.8562,1.7039,5.6829,32.0,740918,27.0
1,0.2282,0.2168,0.8442,1.5287,2.5440,0.1141,0.9355,1.6086,1.6542,5.0082,32.0,652886,25.0
2,0.5249,0.2261,1.2356,1.5183,0.7188,0.0323,0.4119,1.0499,0.6057,2.8912,96.0,30243196,29.0
3,0.5279,0.1760,1.3951,1.8978,0.9677,0.0377,0.2765,0.9175,0.3393,1.9481,30.5,351898,29.0
4,0.5183,0.2073,1.1863,1.3476,1.3591,0.0576,0.3686,1.6470,1.6931,5.3097,48.0,3141100,29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,0.4903,0.1103,1.0052,1.2258,0.5516,0.0858,0.0858,1.2626,1.1400,3.0400,24.0,117844,29.0
91,0.5635,0.1690,1.2209,1.1176,0.4132,0.0751,0.1690,1.2397,1.1082,3.6252,21.5,48391,28.0
92,0.2373,0.1187,0.7120,1.4779,4.0453,0.0216,0.3452,3.0097,1.4671,8.4358,44.0,1028085,28.0
93,0.2798,0.2798,0.9795,3.0083,2.8384,0.0300,0.5297,1.6691,0.6396,4.2876,22.5,8983450,32.0
94,0.3357,0.2662,0.7524,1.2039,0.9260,0.0695,0.3010,1.8637,1.7595,6.6791,24.0,109000,26.0

In [200]:
from sklearn.decomposition import PCA

atk_pca_atk = PCA(n_components=1)
atk_low_atk = atk_pca_atk.fit_transform(atk[col_atk])

In [201]:
atk_pca_basic = PCA(n_components=1)
atk_low_basic = atk_pca_basic.fit_transform(atk[col_basic])

atk_pca_dfd = PCA(n_components=1)
atk_low_dfd = atk_pca_dfd.fit_transform(atk[col_dfd])

atk_pca_cont = PCA(n_components=1)
atk_low_cont = atk_pca_cont.fit_transform(atk[col_cont])

In [202]:
from sklearn.decomposition import PCA

dfd_pca_atk = PCA(n_components=1)
dfd_low_atk = dfd_pca_atk.fit_transform(dfd[col_atk])

In [203]:
dfd_pca_basic = PCA(n_components=1)
dfd_low_basic = dfd_pca_basic.fit_transform(dfd[col_basic])

dfd_pca_dfd = PCA(n_components=1)
dfd_low_dfd = dfd_pca_dfd.fit_transform(dfd[col_dfd])

dfd_pca_cont = PCA(n_components=1)
dfd_low_cont = dfd_pca_cont.fit_transform(dfd[col_cont])

In [204]:
from sklearn.decomposition import PCA

mdf_pca_atk = PCA(n_components=1)
mdf_low_atk = mdf_pca_atk.fit_transform(mdfㅋ[col_atk])

In [205]:
mdf_pca_basic = PCA(n_components=1)
mdf_low_basic = mdf_pca_basic.fit_transform(mdf[col_basic])

mdf_pca_dfd = PCA(n_components=1)
mdf_low_dfd = mdf_pca_dfd.fit_transform(mdf[col_dfd])

mdf_pca_cont = PCA(n_components=1)
mdf_low_cont = mdf_pca_cont.fit_transform(mdf[col_cont])

In [206]:
atk_low_atk = pd.DataFrame(atk_low_atk,columns=['pca_atk'])
atk_low_basic = pd.DataFrame(atk_low_basic,columns=['pca_basic'])
atk_low_dfd = pd.DataFrame(atk_low_dfd,columns=['pca_dfd'])
atk_low_cont = pd.DataFrame(atk_low_cont,columns=['pca_cont'])

In [207]:
atk_pca = pd.concat([atk_low_atk,atk_low_basic,atk_low_dfd,atk_low_cont],axis=1)

In [208]:
atk_value = pd.DataFrame(atk.value,columns=['value'])
atk_follower = pd.DataFrame(atk.follower,columns=['follower'])
atk_age = pd.DataFrame(atk.age,columns=['age'])

In [209]:
dfd_low_atk = pd.DataFrame(dfd_low_atk,columns=['pca_atk'])
dfd_low_basic = pd.DataFrame(dfd_low_basic,columns=['pca_basic'])
dfd_low_dfd = pd.DataFrame(dfd_low_dfd,columns=['pca_dfd'])
dfd_low_cont = pd.DataFrame(dfd_low_cont,columns=['pca_cont'])

In [210]:
dfd_pca = pd.concat([dfd_low_atk,dfd_low_basic,dfd_low_dfd,dfd_low_cont],axis=1)

In [211]:
dfd_value = pd.DataFrame(dfd.value,columns=['value'])
dfd_follower = pd.DataFrame(dfd.follower,columns=['follower'])
dfd_age = pd.DataFrame(dfd.age,columns=['age'])

In [212]:
dfd_pca = pd.concat([dfd_pca,dfd_value,dfd_follower,dfd_age],axis=1)
dfd_pca

     pca_atk  pca_basic   pca_dfd  pca_cont  value  follower   age
0  -0.076421  -0.673603 -0.307250  0.133549   24.0    601838  24.0
1   0.109012   1.078872 -0.046500 -0.495251   28.0    453600  25.0
2   0.189416   1.179655  0.475776 -0.588251   54.0   3118407  22.0
3  -0.031923  -0.534326 -0.162378  0.504949   60.0    841807  26.0
4   0.124776   0.475772 -0.643217 -0.836651   24.0   2696305  26.0
..       ...        ...       ...       ...    ...       ...   ...
90  0.023141   1.005417  1.483554  0.761749   32.0   1804339  23.0
91 -0.059149  -0.438008 -0.008044  0.708149   28.0    417950  24.0
92  0.072758   0.095499 -0.484630 -1.708251   24.0   1155895  29.0
93 -0.062070  -0.622806 -0.630976 -0.742851   28.0   1737260  26.0
94 -0.024270  -0.610622 -0.302780  1.893949   80.0   9310129  29.0

[95 rows x 7 columns]

In [213]:
mdf_low_atk = pd.DataFrame(mdf_low_atk,columns=['pca_atk'])
mdf_low_basic = pd.DataFrame(mdf_low_basic,columns=['pca_basic'])
mdf_low_dfd = pd.DataFrame(mdf_low_dfd,columns=['pca_dfd'])
mdf_low_cont = pd.DataFrame(mdf_low_cont,columns=['pca_cont'])

In [214]:
mdf_pca = pd.concat([mdf_low_atk,mdf_low_basic,mdf_low_dfd,mdf_low_cont],axis=1)

In [215]:
mdf_value = pd.DataFrame(mdf.value,columns=['value'])
mdf_follower = pd.DataFrame(mdf.follower,columns=['follower'])
mdf_age = pd.DataFrame(mdf.age,columns=['age'])

In [216]:
mdf_pca = pd.concat([mdf_pca,mdf_value,mdf_follower,mdf_age],axis=1)
mdf_pca

      pca_atk  pca_basic   pca_dfd  pca_cont  value  follower   age
0   -0.207319  -0.960857 -0.833943 -2.780138   20.0     67879  25.0
1    0.383617   0.868692 -0.676076 -2.704238   32.0  11513791  32.0
2   -0.032763  -0.453671 -0.849799  0.408462   20.0     46206  27.0
3   -0.033089   0.176049  0.513587 -0.653838   20.0     11440  24.0
4   -0.011712   1.002298  2.171597  0.746962   24.0   1019540  23.0
..        ...        ...       ...       ...    ...       ...   ...
146 -0.093769   0.075192 -0.517781 -1.017138   16.0    170526  26.0
147 -0.182249  -1.175762  0.587462  0.533062   16.0    820996  27.0
148 -0.107986  -0.899193 -0.751104  0.511262   20.0    152427  22.0
149 -0.147520  -0.938578 -0.787619  4.338762   36.0    529117  24.0
150 -0.017107  -0.498906  0.079624  0.471662   44.0    282254  23.0

[151 rows x 7 columns]

In [217]:
atk_pca

     pca_atk  pca_basic   pca_dfd  pca_cont
0  -0.041326  -0.791196  1.459412  1.521463
1  -0.243577   0.834247  0.317542  0.846763
2   0.052589  -0.786029 -0.619698 -1.270237
3   0.050621  -0.387844 -0.848914 -2.213337
4   0.044163  -0.285503  0.341540  1.148263
..       ...        ...       ...       ...
90  0.006710  -1.078715 -0.235579 -1.121437
91  0.085355  -1.233598 -0.265061 -0.536237
92 -0.244220   2.155760  1.514933  4.274363
93 -0.186002   1.741268 -0.028959  0.126163
94 -0.131720  -0.769438  0.564025  2.517663

[95 rows x 4 columns]

In [218]:
atk_pca = pd.concat([atk_pca,atk_value,atk_follower,atk_age],axis=1)
atk_pca

     pca_atk  pca_basic   pca_dfd  pca_cont  value  follower   age
0  -0.041326  -0.791196  1.459412  1.521463   32.0    740918  27.0
1  -0.243577   0.834247  0.317542  0.846763   32.0    652886  25.0
2   0.052589  -0.786029 -0.619698 -1.270237   96.0  30243196  29.0
3   0.050621  -0.387844 -0.848914 -2.213337   30.5    351898  29.0
4   0.044163  -0.285503  0.341540  1.148263   48.0   3141100  29.0
..       ...        ...       ...       ...    ...       ...   ...
90  0.006710  -1.078715 -0.235579 -1.121437   24.0    117844  29.0
91  0.085355  -1.233598 -0.265061 -0.536237   21.5     48391  28.0
92 -0.244220   2.155760  1.514933  4.274363   44.0   1028085  28.0
93 -0.186002   1.741268 -0.028959  0.126163   22.5   8983450  32.0
94 -0.131720  -0.769438  0.564025  2.517663   24.0    109000  26.0

[95 rows x 7 columns]

In [219]:
atk_pca = sm.add_constant(atk_pca)

In [220]:
atk_pca_x = atk_pca.drop(columns = 'value')
atk_pca_y = atk_pca.value

In [221]:
from sklearn.model_selection import train_test_split

dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(atk_pca_x, atk_pca_y, test_size=0.3, random_state=0)

In [222]:
dfy_train = pd.DataFrame(dfy_train)
dfy_test = pd.DataFrame(dfy_test)

In [223]:
model = sm.OLS(dfy_train,dfX_train)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  value   R-squared:                       0.466
Model:                            OLS   Adj. R-squared:                  0.411
Method:                 Least Squares   F-statistic:                     8.568
Date:                Mon, 22 Jun 2020   Prob (F-statistic):           1.05e-06
Time:                        22:23:56   Log-Likelihood:                -300.95
No. Observations:                  66   AIC:                             615.9
Df Residuals:                      59   BIC:                             631.2
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         96.7759     25.770      3.755      0.000      45.210     148.342
pca_atk      101.7718     20.254      5.025      0.000      61.244     142.299
pca_basic     13.5385      3.593      3.768      0.000       6.349      20.729
pca_dfd       -4.0530      5.093     -0.796      0.429     -14.245       6.139
pca_cont       0.3993      2.321      0.172      0.864      -4.245       5.044
follower    6.742e-08   1.16e-07      0.580      0.564   -1.65e-07       3e-07
age           -2.0935      0.983     -2.131      0.037      -4.060      -0.127
==============================================================================
Omnibus:                       22.312   Durbin-Watson:                   1.955
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               34.491
Skew:                           1.262   Prob(JB):                     3.24e-08
Kurtosis:                       5.485   Cond. No.                     3.06e+08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.06e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [224]:
df_test = pd.DataFrame(dfX_test)

pred = result.predict(df_test)

rss = ((dfy_test.value - pred) ** 2).sum()
tss = ((dfy_test.value - dfy_test.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.26524559557484495

ridge

In [225]:
result_ridge = model.fit_regularized(alpha=0.01, L1_wt=0)

In [226]:
df_test = pd.DataFrame(dfX_test)

pred = result_ridge.predict(df_test)

rss = ((dfy_test.value - pred) ** 2).sum()
tss = ((dfy_test.value - dfy_test.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.29957849305669015

# 스케일링

In [227]:
df_train = pd.concat([dfX_train,dfy_train],axis=1)
df_train.head()

    const   pca_atk  pca_basic   pca_dfd  pca_cont  follower   age  value
84    1.0  0.059578   0.498076  0.347961  1.812763   7300802  28.0  120.0
87    1.0  0.178699  -0.427725 -0.622239 -2.041437    823676  24.0   64.0
3     1.0  0.050621  -0.387844 -0.848914 -2.213337    351898  29.0   30.5
66    1.0 -0.005085   1.257579  2.095574  1.880063   1052652  27.0   32.0
85    1.0  0.056329  -0.890513 -0.210102  1.130763   1691131  23.0   40.0

In [228]:
import statsmodels.api as sm

model2 = sm.OLS.from_formula('value ~ scale(pca_atk)+scale(pca_basic)+scale(pca_dfd)+\
scale(pca_cont)+np.log(follower)+scale(age)',data = df_train)
result2 = model2.fit()
print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  value   R-squared:                       0.553
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     12.15
Date:                Mon, 22 Jun 2020   Prob (F-statistic):           7.66e-09
Time:                        22:23:58   Log-Likelihood:                -295.09
No. Observations:                  66   AIC:                             604.2
Df Residuals:                      59   BIC:                             619.5
Df Model:                           6
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept          -25.8024     20.534     -1.257      0.214     -66.891      15.286
scale(pca_atk)      14.5561      3.362      4.330      0.000       7.829      21.283
scale(pca_basic)     7.7164      3.735      2.066      0.043       0.242      15.191
scale(pca_dfd)      -1.8745      3.757     -0.499      0.620      -9.391       5.643
scale(pca_cont)      2.0410      3.790      0.539      0.592      -5.542       9.624
np.log(follower)     5.1265      1.487      3.446      0.001       2.150       8.103
scale(age)          -9.4585      3.122     -3.030      0.004     -15.705      -3.212
==============================================================================
Omnibus:                       17.624   Durbin-Watson:                   1.945
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               25.284
Skew:                           1.022   Prob(JB):                     3.23e-06
Kurtosis:                       5.240   Cond. No.                         105.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [229]:
df_test = pd.DataFrame(dfX_test)

pred = result2.predict(df_test)

rss = ((dfy_test.value - pred) ** 2).sum()
tss = ((dfy_test.value - dfy_test.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.4378324259994322

# 스케일링 + 기저 + 정규화

In [230]:
import statsmodels.api as sm

model3 = sm.OLS.from_formula('value ~ scale(pca_atk)+scale(pca_basic)\
+np.log(follower)+scale(age)+scale(I(age**2))+scale(I(age**3))+scale(I(age**4))+scale(I(age**5))+scale(I(age**6))',data = df_train)
result3 = model3.fit()
print(result3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  value   R-squared:                       0.638
Model:                            OLS   Adj. R-squared:                  0.580
Method:                 Least Squares   F-statistic:                     10.98
Date:                Mon, 22 Jun 2020   Prob (F-statistic):           1.26e-09
Time:                        22:23:58   Log-Likelihood:                -288.08
No. Observations:                  66   AIC:                             596.2
Df Residuals:                      56   BIC:                             618.1
Df Model:                           9
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept            -28.5379     19.140     -1.491      0.142     -66.879       9.803
scale(pca_atk)        13.9959      3.171      4.414      0.000       7.644      20.348
scale(pca_basic)       6.0576      3.075      1.970      0.054      -0.101      12.217
np.log(follower)       5.3264      1.387      3.841      0.000       2.548       8.104
scale(age)          1.323e+06   4.38e+05      3.023      0.004    4.46e+05     2.2e+06
scale(I(age ** 2)) -6.558e+06   2.18e+06     -3.010      0.004   -1.09e+07   -2.19e+06
scale(I(age ** 3))  1.315e+07   4.39e+06      2.995      0.004    4.35e+06    2.19e+07
scale(I(age ** 4)) -1.332e+07   4.47e+06     -2.979      0.004   -2.23e+07   -4.36e+06
scale(I(age ** 5))  6.822e+06    2.3e+06      2.961      0.004    2.21e+06    1.14e+07
scale(I(age ** 6)) -1.412e+06    4.8e+05     -2.942      0.005   -2.37e+06    -4.5e+05
==============================================================================
Omnibus:                       13.985   Durbin-Watson:                   1.687
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.156
Skew:                           0.951   Prob(JB):                     0.000310
Kurtosis:                       4.503   Cond. No.                     3.87e+07
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.58e-12. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [231]:
result_ridge3 = model3.fit_regularized(alpha=0.01, L1_wt=0)

In [232]:
df_test = pd.DataFrame(dfX_test)

pred = result_ridge3.predict(df_test)

rss = ((dfy_test.value - pred) ** 2).sum()
tss = ((dfy_test.value - dfy_test.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.49242187562980655

In [233]:
result_lasso3 = model3.fit_regularized(alpha=0.01, L1_wt=1)

In [234]:
df_test = pd.DataFrame(dfX_test)

pred = result_lasso3.predict(df_test)

rss = ((dfy_test.value - pred) ** 2).sum()
tss = ((dfy_test.value - dfy_test.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.4655103300028077

In [235]:
result_ela3 = model3.fit_regularized(alpha=0.01, L1_wt=0.5)

In [236]:
df_test = pd.DataFrame(dfX_test)

pred = result_ela3.predict(df_test)

rss = ((dfy_test.value - pred) ** 2).sum()
tss = ((dfy_test.value - dfy_test.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.4703526692996557

# dfd, mdf 시작

In [237]:
dfd_pca

     pca_atk  pca_basic   pca_dfd  pca_cont  value  follower   age
0  -0.076421  -0.673603 -0.307250  0.133549   24.0    601838  24.0
1   0.109012   1.078872 -0.046500 -0.495251   28.0    453600  25.0
2   0.189416   1.179655  0.475776 -0.588251   54.0   3118407  22.0
3  -0.031923  -0.534326 -0.162378  0.504949   60.0    841807  26.0
4   0.124776   0.475772 -0.643217 -0.836651   24.0   2696305  26.0
..       ...        ...       ...       ...    ...       ...   ...
90  0.023141   1.005417  1.483554  0.761749   32.0   1804339  23.0
91 -0.059149  -0.438008 -0.008044  0.708149   28.0    417950  24.0
92  0.072758   0.095499 -0.484630 -1.708251   24.0   1155895  29.0
93 -0.062070  -0.622806 -0.630976 -0.742851   28.0   1737260  26.0
94 -0.024270  -0.610622 -0.302780  1.893949   80.0   9310129  29.0

[95 rows x 7 columns]

In [238]:
mdf_pca

      pca_atk  pca_basic   pca_dfd  pca_cont  value  follower   age
0   -0.207319  -0.960857 -0.833943 -2.780138   20.0     67879  25.0
1    0.383617   0.868692 -0.676076 -2.704238   32.0  11513791  32.0
2   -0.032763  -0.453671 -0.849799  0.408462   20.0     46206  27.0
3   -0.033089   0.176049  0.513587 -0.653838   20.0     11440  24.0
4   -0.011712   1.002298  2.171597  0.746962   24.0   1019540  23.0
..        ...        ...       ...       ...    ...       ...   ...
146 -0.093769   0.075192 -0.517781 -1.017138   16.0    170526  26.0
147 -0.182249  -1.175762  0.587462  0.533062   16.0    820996  27.0
148 -0.107986  -0.899193 -0.751104  0.511262   20.0    152427  22.0
149 -0.147520  -0.938578 -0.787619  4.338762   36.0    529117  24.0
150 -0.017107  -0.498906  0.079624  0.471662   44.0    282254  23.0

[151 rows x 7 columns]

# 스케일링으로

### dfd

In [239]:
dfd_pca_x = dfd_pca.drop(columns = 'value')
dfd_pca_y = dfd_pca.value

In [240]:
from sklearn.model_selection import train_test_split

dfX_train_dfd, dfX_test_dfd, dfy_train_dfd, dfy_test_dfd = train_test_split(dfd_pca_x, dfd_pca_y, test_size=0.3, random_state=0)

In [241]:
dfy_train_dfd = pd.DataFrame(dfy_train_dfd)
dfy_test_dfd = pd.DataFrame(dfy_test_dfd)

In [242]:
df_train_dfd = pd.concat([dfX_train_dfd,dfy_train_dfd],axis=1)
df_train_dfd = df_train_dfd.reset_index().drop(columns = 'index')
df_train_dfd.head()

    pca_atk  pca_basic   pca_dfd  pca_cont  follower   age  value
0 -0.057383  -0.747497 -0.255446 -1.321151    300512  29.0   25.5
1 -0.058930  -0.647953 -0.992990 -1.302751   2109843  31.0   24.0
2 -0.031923  -0.534326 -0.162378  0.504949    841807  26.0   60.0
3 -0.037487  -0.608049 -0.435709 -0.577851   4987874  21.0   67.5
4 -0.069641  -0.615662  0.413463 -0.567351   6622992  27.0   32.0

In [243]:
import statsmodels.api as sm

model_dfd = sm.OLS.from_formula('value ~ scale(pca_atk)+scale(pca_basic)+scale(pca_dfd)+\
scale(pca_cont)+np.log(follower)+scale(age)',data = df_train_dfd)
result_dfd = model_dfd.fit()
print(result_dfd.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  value   R-squared:                       0.319
Model:                            OLS   Adj. R-squared:                  0.249
Method:                 Least Squares   F-statistic:                     4.600
Date:                Mon, 22 Jun 2020   Prob (F-statistic):           0.000680
Time:                        22:24:01   Log-Likelihood:                -250.47
No. Observations:                  66   AIC:                             514.9
Df Residuals:                      59   BIC:                             530.3
Df Model:                           6
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept          -21.7058     12.970     -1.674      0.100     -47.659       4.248
scale(pca_atk)       5.6817      3.131      1.815      0.075      -0.583      11.946
scale(pca_basic)    -6.7544      3.441     -1.963      0.054     -13.640       0.131
scale(pca_dfd)       0.9892      1.928      0.513      0.610      -2.869       4.848
scale(pca_cont)      0.2926      1.757      0.167      0.868      -3.223       3.808
np.log(follower)     4.0238      0.964      4.172      0.000       2.094       5.954
scale(age)          -7.6625      1.692     -4.528      0.000     -11.049      -4.276
==============================================================================
Omnibus:                        3.388   Durbin-Watson:                   1.362
Prob(Omnibus):                  0.184   Jarque-Bera (JB):                3.310
Skew:                           0.527   Prob(JB):                        0.191
Kurtosis:                       2.697   Cond. No.                         126.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [244]:
df_test = pd.DataFrame(dfX_test_dfd)

pred = result_dfd.predict(df_test)

rss = ((dfy_test_dfd.value - pred) ** 2).sum()
tss = ((dfy_test_dfd.value - dfy_test_dfd.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.2969039092300064

In [245]:
df_test

     pca_atk  pca_basic   pca_dfd  pca_cont  follower   age
2   0.189416   1.179655  0.475776 -0.588251   3118407  22.0
30 -0.025013  -0.074682 -0.143794  1.570749   1885986  27.0
56  0.017604   0.492388  0.298943  0.448649     66558  20.0
16 -0.052452  -0.624167  0.054887 -0.169951   1835812  25.0
13 -0.036021  -0.330230  0.416315 -0.381451    408100  21.0
61  0.066221   0.598623  0.195973  0.568449      1810  30.0
62  0.086885   0.920176  0.083779  0.735749     43758  29.0
80  0.025188   1.260732  0.476288  1.997049    574586  21.0
33  0.169351   0.547337 -0.043959 -1.569351  12699789  31.0
79  0.112556   1.182093 -0.162283 -1.596451    684951  27.0
76 -0.075162  -0.506387  0.456819 -0.832051   2500000  25.0
7   0.030526   0.954990  1.027713  1.298749   1971364  29.0
51  0.089056   1.013118  0.235137  1.641449   1964483  27.0
90  0.023141   1.005417  1.483554  0.761749   1804339  23.0
94 -0.024270  -0.610622 -0.302780  1.893949   9310129  29.0
60 -0.068464  -0.596922 -0.038151 -1.107851     72468  24.0
8   0.201143   1.311115  0.066327 -1.227551    923192  28.0
22 -0.085777  -0.478864  0.431696 -0.057651     17900  29.0
73 -0.052259  -0.649811 -0.479429 -0.779151    625272  25.0
45 -0.052807  -0.732070 -0.179357 -0.971051    602431  29.0
26 -0.029090  -0.375035  0.518458 -1.131551    139915  24.0
43 -0.059704  -0.557030 -0.074225  2.968849     23274  28.0
24 -0.038230  -0.295282 -0.233544  1.339749    536092  23.0
6  -0.063232  -0.645614 -0.396388 -0.055651   1242810  27.0
42 -0.042198  -0.409331 -0.383861 -0.630151    178394  24.0
48  0.018063   0.167365 -0.346720  0.042949   1786433  30.0
74  0.070757   0.168731  1.595940  0.533149   1049277  28.0
88  0.206171   0.981927 -0.511673 -0.925451   4360128  22.0
78  0.076414   0.233475  0.467417 -0.246351     66299  26.0

In [246]:
df_train

    const   pca_atk  pca_basic   pca_dfd  pca_cont  follower   age  value
84    1.0  0.059578   0.498076  0.347961  1.812763   7300802  28.0  120.0
87    1.0  0.178699  -0.427725 -0.622239 -2.041437    823676  24.0   64.0
3     1.0  0.050621  -0.387844 -0.848914 -2.213337    351898  29.0   30.5
66    1.0 -0.005085   1.257579  2.095574  1.880063   1052652  27.0   32.0
85    1.0  0.056329  -0.890513 -0.210102  1.130763   1691131  23.0   40.0
..    ...       ...        ...       ...       ...       ...   ...    ...
91    1.0  0.085355  -1.233598 -0.265061 -0.536237     48391  28.0   21.5
67    1.0  0.018435  -0.808729  0.186500 -0.503737     30993  24.0   17.5
64    1.0 -0.126587   0.712208  0.435053  1.670963       377  23.0   22.5
47    1.0 -0.066426  -0.594381  0.145857 -0.911837    176399  28.0   40.0
44    1.0 -0.295659  -1.756237 -1.708222 -3.981937    197203  21.0   16.0

[66 rows x 8 columns]

In [247]:
df_train_dfd

     pca_atk  pca_basic   pca_dfd  pca_cont  follower   age  value
0  -0.057383  -0.747497 -0.255446 -1.321151    300512  29.0   25.5
1  -0.058930  -0.647953 -0.992990 -1.302751   2109843  31.0   24.0
2  -0.031923  -0.534326 -0.162378  0.504949    841807  26.0   60.0
3  -0.037487  -0.608049 -0.435709 -0.577851   4987874  21.0   67.5
4  -0.069641  -0.615662  0.413463 -0.567351   6622992  27.0   32.0
..       ...        ...       ...       ...       ...   ...    ...
61 -0.059149  -0.438008 -0.008044  0.708149    417950  24.0   28.0
62 -0.011465  -0.628618 -0.586310 -1.593451   3115459  26.0   52.0
63 -0.048905  -0.663640 -0.559532  2.085149    122044  27.0   20.0
64  0.104493   1.124736 -0.122082 -0.277151    691216  30.0   28.0
65 -0.045882  -0.442260 -0.184119 -0.470151   1443167  29.0   24.0

[66 rows x 7 columns]

# 스케일링으로

### mdf

In [248]:
mdf_pca_x = mdf_pca.drop(columns = 'value')
mdf_pca_y = mdf_pca.value

In [249]:
from sklearn.model_selection import train_test_split

dfX_train_mdf, dfX_test_mdf, dfy_train_mdf, dfy_test_mdf = train_test_split(mdf_pca_x, mdf_pca_y, test_size=0.3, random_state=0)

In [250]:
dfy_train_mdf = pd.DataFrame(dfy_train_mdf)
dfy_test_mdf = pd.DataFrame(dfy_test_mdf)

In [251]:
mdf_pca[mdf_pca.pca_atk.isnull()]

Empty DataFrame
Columns: [pca_atk, pca_basic, pca_dfd, pca_cont, value, follower, age]
Index: []

In [252]:
df_train_mdf = pd.concat([dfX_train_mdf,dfy_train_mdf],axis=1)
df_train_mdf = df_train_dfd.reset_index().drop(columns = 'index')
df_train_mdf.head()

    pca_atk  pca_basic   pca_dfd  pca_cont  follower   age  value
0 -0.057383  -0.747497 -0.255446 -1.321151    300512  29.0   25.5
1 -0.058930  -0.647953 -0.992990 -1.302751   2109843  31.0   24.0
2 -0.031923  -0.534326 -0.162378  0.504949    841807  26.0   60.0
3 -0.037487  -0.608049 -0.435709 -0.577851   4987874  21.0   67.5
4 -0.069641  -0.615662  0.413463 -0.567351   6622992  27.0   32.0

In [253]:
import statsmodels.api as sm

model_mdf = sm.OLS.from_formula('value ~ scale(pca_atk)+scale(pca_basic)+scale(pca_dfd)+\
scale(pca_cont)+np.log(follower)+scale(age)',data = df_train_mdf)
result_mdf = model_mdf.fit()
print(result_mdf.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  value   R-squared:                       0.319
Model:                            OLS   Adj. R-squared:                  0.249
Method:                 Least Squares   F-statistic:                     4.600
Date:                Mon, 22 Jun 2020   Prob (F-statistic):           0.000680
Time:                        22:24:04   Log-Likelihood:                -250.47
No. Observations:                  66   AIC:                             514.9
Df Residuals:                      59   BIC:                             530.3
Df Model:                           6
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept          -21.7058     12.970     -1.674      0.100     -47.659       4.248
scale(pca_atk)       5.6817      3.131      1.815      0.075      -0.583      11.946
scale(pca_basic)    -6.7544      3.441     -1.963      0.054     -13.640       0.131
scale(pca_dfd)       0.9892      1.928      0.513      0.610      -2.869       4.848
scale(pca_cont)      0.2926      1.757      0.167      0.868      -3.223       3.808
np.log(follower)     4.0238      0.964      4.172      0.000       2.094       5.954
scale(age)          -7.6625      1.692     -4.528      0.000     -11.049      -4.276
==============================================================================
Omnibus:                        3.388   Durbin-Watson:                   1.362
Prob(Omnibus):                  0.184   Jarque-Bera (JB):                3.310
Skew:                           0.527   Prob(JB):                        0.191
Kurtosis:                       2.697   Cond. No.                         126.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [254]:
df_test = pd.DataFrame(dfX_test_mdf)

pred = result_mdf.predict(df_test)

rss = ((dfy_test_mdf.value - pred) ** 2).sum()
tss = ((dfy_test_mdf.value - dfy_test_mdf.value.mean()) ** 2).sum()
rsquared = 1 - rss / tss
rsquared

0.06965251142611106