In [5]:
df1 = pd.read_csv('/Users/kimjeongseob/Desktop/Github upload/5.EDA/EDA 프로젝트/2차 _ 분석/csv 모음/(4) 마지막 버젼 4컬럼_정한.csv')
df1 = df1.drop(columns = ['Current_Ver', 'Ver_Mon', 'Ver_Year', 'And_1st_Ver', 'And_Last_Ver'])

In [23]:
df1 = pd.read_csv('/Users/kimjeongseob/Desktop/Github upload/5.EDA/EDA 프로젝트/2차 _ 분석/csv 모음/(1).csv')
df2 = pd.read_csv('/Users/kimjeongseob/Desktop/Github upload/5.EDA/EDA 프로젝트/2차 _ 분석/csv 모음/(2).csv')
df3 = pd.read_csv('/Users/kimjeongseob/Desktop/Github upload/5.EDA/EDA 프로젝트/2차 _ 분석/csv 모음/(3).csv')
df4 = pd.read_csv('/Users/kimjeongseob/Desktop/Github upload/5.EDA/EDA 프로젝트/2차 _ 분석/csv 모음/(4).csv')
df4

      Current_Ver  Ver_Mon  Ver_Year  And_1st_Ver  And_Last_Ver
0           1.0.0      1.0    2018.0          4.0          11.0
1           2.0.0      1.0    2018.0          4.0          11.0
2           1.2.4      8.0    2018.0          4.0          11.0
3           1.0.0      6.0    2018.0          4.0          11.0
4             1.1      6.0    2018.0          4.0          11.0
...           ...      ...       ...          ...           ...
10834        1.48      7.0    2017.0          4.0          11.0
10835         1.0      7.0    2018.0          4.0          11.0
10836         1.0      1.0    2017.0          2.0          11.0
10837       1.0.0      1.0    2015.0         11.0          11.0
10838       1.0.0      7.0    2018.0         11.0          11.0

[10839 rows x 5 columns]

In [11]:
data = df1
col_df2 = ['Size','Installs','Type']
col_df3 = ['Price','Content Rating','Genres','pri_genres','sec_genres']
col_df4 = ['Current_Ver','Ver_Mon','Ver_Year','And_1st_Ver','And_Last_Ver']

In [26]:
data['Size'] = df2['Size']
data['Installs'] =df2['Installs']
data['Type'] = df2['Type']
data['Price'] = df3['Price']
data['Content Rating'] = df3['Content Rating']
data['Genres'] = df3['Genres']
data['pri_genres'] = df3['pri_genres']
data['sec_genres'] = df3['sec_genres']
data['Current_Ver'] = df4['Current_Ver']
data['Ver_Mon'] = df4['Ver_Mon']
data['Ver_Year'] = df4['Ver_Year']
data['And_1st_Ver'] = df4['And_1st_Ver']
data['And_Last_Ver'] = df4['And_Last_Ver']
data = data.drop(columns = ['Unnamed: 0'])
data

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,pri_genres,sec_genres,Current_Ver,Ver_Mon,Ver_Year,And_1st_Ver,And_Last_Ver
0,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,0.0,0.0,Everyone,Art & Design,Art & Design,Art & Design,1.0.0,1.0,2018.0,4.0,11.0
1,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,0.0,0.0,Everyone,Art & Design;Pretend Play,Art & Design,Pretend Play,2.0.0,1.0,2018.0,4.0,11.0
2,ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,0.0,0.0,Everyone,Art & Design,Art & Design,Art & Design,1.2.4,8.0,2018.0,4.0,11.0
3,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,0.0,0.0,Teen,Art & Design,Art & Design,Art & Design,1.0.0,6.0,2018.0,4.0,11.0
4,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,0.0,0.0,Everyone,Art & Design;Creativity,Art & Design,Creativity,1.1,6.0,2018.0,4.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FAMILY,4.5,38.0,53.0,5000.0,0.0,0.0,Everyone,Education,Education,Education,1.48,7.0,2017.0,4.0,11.0
10835,FAMILY,5.0,4.0,3.6,100.0,0.0,0.0,Everyone,Education,Education,Education,1.0,7.0,2018.0,4.0,11.0
10836,MEDICAL,0.0,3.0,9.5,1000.0,0.0,0.0,Everyone,Medical,Medical,Medical,1.0,1.0,2017.0,2.0,11.0
10837,BOOKS_AND_REFERENCE,4.5,114.0,37.0,1000.0,0.0,0.0,Mature 17+,Books & Reference,Books & Reference,Books & Reference,1.0.0,1.0,2015.0,11.0,11.0
10838,LIFESTYLE,4.5,398307.0,19.0,10000000.0,0.0,0.0,Everyone,Lifestyle,Lifestyle,Lifestyle,1.0.0,7.0,2018.0,11.0,11.0

In [28]:
data.to_csv('/Users/kimjeongseob/Desktop/Github upload/5.EDA/EDA 프로젝트/2차 _ 분석/데이터.csv',header = ['Category','Rating','reviews','Size','Installs','Type','Price','Content Rating','Genres','pri_genres','sec_genres','Current_Ver','Ver_Mon','Ver_Year','And_1st_Ver','And_Last_Ver'],index = True)

In [29]:
data

,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,pri_genres,sec_genres,Current_Ver,Ver_Mon,Ver_Year,And_1st_Ver,And_Last_Ver
0,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,0.0,0.0,Everyone,Art & Design,Art & Design,Art & Design,1.0.0,1.0,2018.0,4.0,11.0
1,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,0.0,0.0,Everyone,Art & Design;Pretend Play,Art & Design,Pretend Play,2.0.0,1.0,2018.0,4.0,11.0
2,ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,0.0,0.0,Everyone,Art & Design,Art & Design,Art & Design,1.2.4,8.0,2018.0,4.0,11.0
3,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,0.0,0.0,Teen,Art & Design,Art & Design,Art & Design,1.0.0,6.0,2018.0,4.0,11.0
4,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,0.0,0.0,Everyone,Art & Design;Creativity,Art & Design,Creativity,1.1,6.0,2018.0,4.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FAMILY,4.5,38.0,53.0,5000.0,0.0,0.0,Everyone,Education,Education,Education,1.48,7.0,2017.0,4.0,11.0
10835,FAMILY,5.0,4.0,3.6,100.0,0.0,0.0,Everyone,Education,Education,Education,1.0,7.0,2018.0,4.0,11.0
10836,MEDICAL,0.0,3.0,9.5,1000.0,0.0,0.0,Everyone,Medical,Medical,Medical,1.0,1.0,2017.0,2.0,11.0
10837,BOOKS_AND_REFERENCE,4.5,114.0,37.0,1000.0,0.0,0.0,Mature 17+,Books & Reference,Books & Reference,Books & Reference,1.0.0,1.0,2015.0,11.0,11.0
10838,LIFESTYLE,4.5,398307.0,19.0,10000000.0,0.0,0.0,Everyone,Lifestyle,Lifestyle,Lifestyle,1.0.0,7.0,2018.0,11.0,11.0